name: nexly_example
description: Demo app for the Nexly Flutter SDK.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  nexly:
    path: ../
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
